### ISSUE TITLE
What are the best settings for most accurate/perfect time stamps?

### ISSUE THREAD

**Issue by silvacarl2** [linto-ai/whisper-timestamped#101]
What are the best settings for most accurate/perfect time stamps?

does not matter how resource it needs to do so.

**Comment by Jeronymous** [comment]
There is a section dedicated to the best options for whisper-timestamped: https://github.com/linto-ai/whisper-timestamped#options-that-may-improve-results

Also, for a better transcription:
* you should use `large-v2` model, or a model finetuned on HuggingFace on your language of interest.
*  `condition_on_previous_text=False` is often recommended to avoid hallucinations.

**Comment by silvacarl2** [comment]
excellent thx!
