### ISSUE TITLE
Why does it take so long to process a 1 minute video?

### ISSUE THREAD

**Issue by Root-FTW** [linto-ai/whisper-timestamped#110]
How can I make it run faster? It takes too long for a 1 minute video. 

![image](https://github.com/linto-ai/whisper-timestamped/assets/108767514/8675aa10-6afd-4c2b-b3a8-179caf3bcb38)

I am using this CLI command:
whisper_timestamped --accurate video.mp4 --model large-v1 --output_format srt --vad False --device "cuda:0" --output_dir .

My PC:

Windows 11 PRO
GPU: GTX 1080 TI
CPU: i9-9900k

**Comment by Jeronymous** [comment]
How much does it take? dozens of minutes?

That is weird. Is there a chance you can share the video?
Is the transcription (almost) correct?

**Comment by IntendedConsequence** [comment]
Something doesn't feel right. When I run with `--model large-v3`, VRAM shoots to 10GB and it's all very slow. And yet, running the large-v3 model in whisper.cpp, and using vanilla transformers pipeline (in this notebook https://huggingface.co/spaces/hf-audio/whisper-large-v3/blob/main/whisper_notebook.ipynb), both of them only use about 4GB VRAM, and are noticeably faster.
