### ISSUE TITLE
simple split audio file example using whisper-timestamped

### ISSUE THREAD

**Issue by silvacarl2** [linto-ai/whisper-timestamped#111]
do you have a simple split audio file example using whisper-timestamped floating around?

8-)

**Comment by silvacarl2** [comment]
i apologzie i was not more clear.  given the output from whisper-timetamped, are you aware of a simple tool that can read its json output once it has processed an audio file in MP3 and then produce MP3 output that splits the original MP3 by word into individual MP3 clips that contain each word?

this could/would be extremely helpful for batch processing a large amount of audio data into indivial clips.

**Comment by Jeronymous** [comment]
Interesting.

But that's another project, that should be more generic, just not linked to the notion of words.
Something that takes an audio, timestamp intervals (in usual format) and split the audio.
