### ISSUE TITLE
NumbaDeprecationWarning

### ISSUE THREAD

**Issue by xjq284** [linto-ai/whisper-timestamped#114]
whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):

**Comment by Jeronymous** [comment]
This warning is not caused because of whisper-timestamped.
Maybe because of openai-whisper. Maybe because of some particular installation settings.
