### ISSUE TITLE
Max length using python

### ISSUE THREAD

**Issue by jeff11-1-1** [linto-ai/whisper-timestamped#127]
hello sir, thanks for this amazing work you've done so far.
I have a rather simple problem but since I'm not familiar with programing a lot, I'm facing it.
I want to use the max length argument in python, is there any way you can add some documentation on how to add this argument to a python code, or maybe there already is a documentation, but sadly I couldn't find it.

Thank you so much!

**Comment by Jeronymous** [comment]
Thank you.

It's hard to guess what you want to do.
What is the "max length argument"?
Are you referring to the maximum number of tokens generated with LLM in general?

Maybe you want to show what you have (some python code?) and describe what you want to achieve?
