### ISSUE TITLE
Issue with large-v3 model testing and channel mismatch error during audio processing 

### ISSUE THREAD

**Issue by Nondzu** [linto-ai/whisper-timestamped#132]
🐛 **Bug Report**

### Description
📝 During the testing phase of the large-v3 model, a channel mismatch error occurred immediately after the progress bar reached completion.

### Progress and Error Details
✅ The progress bar reported successful completion:
```
Progress: 662363/662363 (100.00%)
```

### Error and Stack Trace
🚫 The error surfaced post completion:
```
An error occurred while processing audio : Given groups=1, weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels instead
```

### Requested Action
🔍 I request an examination of the error post-progress completion, particularly the channel size expectation mismatch in the audio processing component.

**Comment by raivisdejus** [comment]
I also get this error. I think the internal structure of v3 whisper models differs, so we get the error.

**Comment by Jeronymous** [comment]
Thanks for notifying.
The number of mel features changed with large-v3.

So decoding was failing with non some default options

**Comment by Nondzu** [comment]
### @Jeronymous Thank you !

#### I'll try it today
