### ISSUE TITLE
Large-v3

### ISSUE THREAD

**Issue by takefy-dev** [linto-ai/whisper-timestamped#134]
![image](https://github.com/linto-ai/whisper-timestamped/assets/79745753/663045c4-02bc-4a83-a7b1-9e7c79d06ff4)

**Comment by Jeronymous** [comment]
Can you give more details about the command line you run?
(and if possible share the input audio as well)

Also what does it give when you run the CLI with `--versions`?

Thanks

**Comment by takefy-dev** [comment]
Hey I run with python like the example whsiper.transcript("preview.mp4")

The only thing is the model I select large-v3 and it's only doing this with large v3. And with all videos

**Comment by Jeronymous** [comment]
OK thanks, I'll check what's happening with large-v3 which was released recently and not tested with whisper-timestamped yet.

**Comment by Jeronymous** [comment]
Just can you please give me the output of
```
import whisper, whisper_timestamped
print(whisper.__version__)
print(whisper_timestamped.__version__)
```

**Comment by takefy-dev** [comment]
> OK thanks, I'll check what's happening with large-v3 which was released recently and not tested with whisper-timestamped yet.

Ok thanks
<img width="326" alt="image" src="https://github.com/linto-ai/whisper-timestamped/assets/79745753/49b28820-38c7-4063-b647-b70e1bcda3e6">

**Comment by takefy-dev** [comment]
Also curious to know what GPU (ec2 )  do you recommend for running 50-min videos.

**Comment by takefy-dev** [comment]
Hey any news?

**Comment by Jeronymous** [comment]
I updated things to improve the support of the new model (large-v3).
Can you retry with the latest version?
Maybe it solves this issue.

If it does not, is it possible for you to share the audio (and the exact command/code you launch)?
Because I could not reproduce this issue.

**Comment by takefy-dev** [comment]
Yeah I let you know Jérôme

**Comment by darnn** [comment]
For the record, with a fresh install of Whisper-TS here, it seemed to work on the one-minute file I tried it on. My GPU's not powerful enough to run large at all, so I used the CPU, if it matters. V1, V2 and V3 were about the same, both in time and in output. Some things are better in 3, some worse, but I guess that doesn't have anything to do with Whisper-TS one way or the other.

**Comment by takefy-dev** [comment]
It seems to work now on an ec2 instance I will test with a T4 gpu
