### ISSUE TITLE
How to get the progress bar when transcribing through a Celery task ?

### ISSUE THREAD

**Issue by dchapelet** [linto-ai/whisper-timestamped#135]
Hi,
I have two issues for get the progress bar when transcribing through a Celery task.
1. I replaced the tqdm.tqdm progress bar in whisper_timestamped itself but I get this error message : AttributeError: module 'whisper_timestamped.transcribe' has no attribute 'tqdm'
```
import whisper_timestamped.transcribe
class _CustomProgressBar(tqdm.tqdm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._current = self.n  # Set the initial value
       .../....
        
    def update(self, n):
        super().update(n)
        self._current += n
       .../...

transcribe_module = sys.modules['whisper_timestamped.transcribe']
transcribe_module.tqdm.tqdm = _CustomProgressBar
```
2. I need to configure Celery to disable standard output "CELERY_WORKER_REDIRECT_STDOUTS = False", otherwise I get this error message : AttributeError: 'LoggingProxy' object has no attribute 'buffer'
Thank you for your help.
David.

**Comment by Jeronymous** [comment]
For the first issue i think you only need to do:
```tqdm.tqdm = _CustomProgressBar```

For the second issue, it should be fixed now.
If it fails with another error (?), you can still try whisper_timestamped.transcribe with option `verbose=False`

**Comment by dchapelet** [comment]
Thank you very for your hotfix
