### ISSUE TITLE
"TypeError: can't convert cuda:0 device type tensor to numpy" with option --plot / plot_word_alignment on CUDA

### ISSUE THREAD

**Issue by WentingMiao** [linto-ai/whisper-timestamped#14]
I clone and setup whisper-timestamped, and it runs well when in CPU version.

But when I want to transcribe and get the mel-spectogram,  error appeared.
![image](https://user-images.githubusercontent.com/55959544/213743839-acbaa59d-bd2a-4ca5-b5a5-15df1c6c4b39.png)

**Comment by Jeronymous** [comment]
Thanks for reporting!
Should be fixed now

**Comment by WentingMiao** [comment]
> Thanks for reporting! Should be fixed now

Hello. Did you new update solving this problem?

**Comment by Jeronymous** [comment]
Yes, as mentioned, the last version does not have this bug.

The commit that solved the bug is mentioned in the log of this issue above
> [Jeronymous](https://github.com/Jeronymous) closed this as completed in [d694a8d](https://github.com/linto-ai/whisper-timestamped/commit/d694a8d249da13e291af3506c9c1e0aacd00a554) 3 days ago

**Comment by WentingMiao** [comment]
my version is whisper-timestamped==1.6.4

**Comment by Jeronymous** [comment]
Hmm I have doubt about your version, I don't recognize the code in the stack as the last version.
Also it seems to fail at at a different place.
Can you check the version by doing in python
```
import whisper_timestamped
whisper_timestamped.__version__
```

**Comment by WentingMiao** [comment]
![image](https://user-images.githubusercontent.com/55959544/214795500-73934dec-f177-4f10-99f5-27d9252da0c8.png)
It's the version I print in the terminal through `pip list`

**Comment by WentingMiao** [comment]
Umm, I reboot it and it works now! Thanks for fixing the bug
