### ISSUE TITLE
everytime I update this, it bricks my python install

### ISSUE THREAD

**Issue by GuyARoss** [linto-ai/whisper-timestamped#145]
Every time I update by uninstalling from the GitHub link, and then installing from the GitHub link it bricks my Python install. It loves to throw that "xzy version of blah is incompatible". Then breaks my program of course.. then I have to go through the cycle of installing everything and reinstalling everything around this package. Plz fix.

**Comment by Jeronymous** [comment]
The requirements of this package are quite minimal to allow people to work in different configurations.
So I am quite surprised to hear this.

Can you say what is xzy and blah (in"xzy version of blah is incompatible")?
And how do you uninstall and reinstall exactly?
