### ISSUE TITLE
Beam Search Decoding How to Get Beam of Tokens as Output

### ISSUE THREAD

**Issue by abarcovschi** [linto-ai/whisper-timestamped#146]
I am looking to get a time-aligned word-level transcript output, but instead of just the best hypothesis, I want to get N best tokens for each token location, i.e. for each word location, I want the N best predicted words and the time for that location (beam size = N).

For example, with a beam size of 2:

**What I approximately get now:**

{
  ...
  "segments": [
    {
      ...
      "text": "I can see clearly",
      ...
      "words": [
        {
          "text": "I",
          "start": 2.02,
          "end": 3.78,
          "confidence": 0.441
        },
        {
          "text": "can",
          "start": 3.78,
          "end": 3.84,
          "confidence": 0.948
        },
        {
          "text": "see",
          "start": 3.84,
          "end": 4.0,
          "confidence": 0.935
        },
        {
          "text": "clearly",
          "start": 4.0,
          "end": 4.14,
          "confidence": 0.347
        }
      ]
    }
  ],
  ...
}

**Theoretically what I am looking for:** 

{
   ...
  "segments": [
    {
      ...
      "text": "I can see clearly",
      ...
      "words": [
        {
          "text": ["I", "eye"],
          "start": 2.02,
          "end": 3.78,
          "confidence": 0.441
        },
        {
          "text": ["can", "cam"],
          "start": 3.78,
          "end": 3.84,
          "confidence": 0.948
        },
        {
          "text": ["see" "sea"],
          "start": 3.84,
          "end": 4.0,
          "confidence": 0.935
        },
        {
          "text": ["clearly", "freely"],
          "start": 4.0,
          "end": 4.14,
          "confidence": 0.347
        }
      ]
    }
  ],
  ...
}

I am transcribing using the following function call:
`result = whisper.transcribe(model, audio, beam_size=5, best_of=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0))`

Is what I am looking for possible?

**Comment by Jeronymous** [comment]
> Is what I am looking for possible?

Having a set of hypothesis for the words makes sense.
But having timestamps for all the alternatives is not really possible.
Also the confidence score should be different for all alternatives.

And this is more a request for openai-whisper, not whisper-timestamped.

**Comment by abarcovschi** [comment]
I would be happy with having multiple hypotheses for the words, and using the timestamp of the top candidate. Also I don't need the confidence scores for my voting algorithm that I am implementing.

Do you think you could at least provide as output N hypotheses in full, instead of word-by-word N hypotheses? Or is this also an openai-whisper request? I just don't know how I would then proceed to extract timestamps for each word in each full hypothesis.

**Comment by abarcovschi** [comment]
I managed to modify the openai-whisper `transcribe.py` and `decoding.py` files to return multiple hypotheses to whisper-timestamped `transcribe.py`. From there, I was able to extract word-level time alignments for each hypotheses by modifying some of the code. I can provide more details if anyone needs to extract word-level time alignments for multiple hypotheses.
