### ISSUE TITLE
Consider using whisper-distilled

### ISSUE THREAD

**Issue by boxabirds** [linto-ai/whisper-timestamped#148]
I love this tool it’s really fantastic. Has there been any thoughts around migrating to using [distilled-whisper](https://github.com/huggingface/distil-whisper)? It’s half the size and six times faster.

**Comment by darnn** [comment]
As of now, Distilled is only available in English, FWIW.

**Comment by Jeronymous** [comment]
It's possible to use distilled models in whisper-timestamped
using `--model=distil-whisper/distil-large-v2` for instance

(any model from HuggingFace should be compitable. If not, please open an issue)
