### ISSUE TITLE
Publication on Pypi failing

### ISSUE THREAD

**Issue by Jeronymous** [linto-ai/whisper-timestamped#149]
see https://github.com/linto-ai/whisper-timestamped/actions/runs/7142325918/job/19451389880
There is an error
```
Run python /home/runner/work/_actions/etils-actions/pypi-auto-publish/v1/src/compare_version.py \
Traceback (most recent call last):
  File "/home/runner/work/_actions/etils-actions/pypi-auto-publish/v1/src/compare_version.py", line 146, in <module>
    main()
  File "/home/runner/work/_actions/etils-actions/pypi-auto-publish/v1/src/compare_version.py", line 45, in main
    pkg_name = find_pkg_name()
  File "/home/runner/work/_actions/etils-actions/pypi-auto-publish/v1/src/compare_version.py", line 78, in find_pkg_name
    raise ValueError(
ValueError: Could not auto-infer the package name: []. Please open an issue.
Error: Process completed with exit code 1.
```
@beveradb @bennyo27 Any idea how to fix this?

Note:
The name of the package is defined in [setup.py](https://github.com/linto-ai/whisper-timestamped/blob/master/setup.py#L22)

Also for the record :
I noticed the package was not automatically published on https://pypi.org/project/whisper-timestamped/#history
So I did this change to fix this: https://github.com/linto-ai/whisper-timestamped/commit/66f54ca71d44b8e3020963149eaee1e643443983 (it seems that the name of the branch was wrong)
Now I just wonder how it previously worked for version 1.13.3 ...

**Comment by bennyo27** [comment]
I see, we can try manually inputting the pkg_name, as per the instructions here https://github.com/etils-actions/pypi-auto-publish.
![image](https://github.com/linto-ai/whisper-timestamped/assets/39509363/2b8d69b9-da73-47aa-a456-b19e3937486b)

**Comment by bennyo27** [comment]
For that issue, I think we should just be able to use the readme?
```
with open("README.md", encoding='utf-8') as f:
    long_description = f.read()

setup(
    # Add long description from README file
    long_description=long_description,
    long_description_content_type='text/markdown',
```

I think there is a way to test github actions locally but I'm not familiar with it
https://github.com/nektos/act

It could be that github actions adds something to the flow of the pypi upload and that's why there are discrepancies in the builds

**Comment by bennyo27** [comment]
That is great to hear!
