### ISSUE TITLE
Got infinite logprob

### ISSUE THREAD

**Issue by tkorchagin** [linto-ai/whisper-timestamped#15]
Using this track:
https://drive.google.com/file/d/1-tunB84weKDR_uIA6raGG9vJS1H34YEL/view?usp=share_link

I got this error:
track.wav
 93%|█████████▎| 443400/475781 [00:52<00:03, 8523.11frames/s]Got infinite logprob

base model

**Comment by tkorchagin** [comment]
python3

```
import whisper_timestamped as whisper
model = whisper.load_model("base")
audio = whisper.load_audio(audio_path)
result = whisper.transcribe(model, audio, language='ru')
```

**Comment by Jeronymous** [comment]
I was asking the version of this package.
If you used pip to install, you should see it with:
```
pip freeze | grep whisper
```
And you should see version 1.5.4 if you're up to date.
If not try:
```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/Jeronymous/whisper-timestamped
```

**Comment by tkorchagin** [comment]
@Jeronymous I use google colab and it resets virtual machine every time

Still got the same error here commands as you asked:

```
!pip freeze | grep whisper

openai-whisper @ git+https://github.com/openai/whisper.git@9f7aba609971434b9de2a8d34ca2de766976904d
whisper-timestamped @ git+https://github.com/Jeronymous/whisper-timestamped@826778f91f9dbadbd80b6f86df64e7352b0c9796
```

**Comment by samheutmaker** [comment]
I'm also having the same issue on the latest version.

**Comment by Jeronymous** [comment]
Thank you @tkorchagin for your effort to help narrowing this down.
Unfortunately I am not able to reproduce your audio `ekaterina_koval 05.01.2023, 17-31.wav` with the base model.
Neither on CPU nor GPU (I also tried other model sizes, to be sure).

Maybe @samheutmaker can share the audio and option details to check if I have "more chance" with his case?

**Comment by Jeronymous** [comment]
@tkorchagin I pushed a new version, where the assertion failure give more details (the list of logprobs).
I would appreciate if you can re-run the transcription that fails and share the new failure message. Maybe I can see something obvious...

Also, you can use option `compute_word_confidence = False` in transcribe().
This should prevent the failure to occur (just you won't have word confidence). Then I'm interested in seeing the output you get (sharing the json file would be awesome). To try to understand why I cannot reproduce your issue...

**Comment by Jeronymous** [comment]
I'm assuming that it's not occurring on the latest version.
Feel free to re-open (and give details) if it occurs again.

**Comment by Rtut654** [comment]
@Jeronymous 
I'm getting similar issue once in ~ 30 function calling. Probably can't share audio since it is user's data, but the log is here:
```
File "/home/test/rep/rep/lib/python3.8/site-packages/whisper_timestamped/transcribe.py", line 688, in may_flush_segment
    assert min([p.isfinite().item() for p in logprobs]), \
AssertionError: Got infinite logprob among (24) [(286, ' I', -inf), (519, ' think', -5.2494893074035645), (8815, ' television', -16.253812789916992), (815, ' may', -10.85153293
6096191), (362, ' have', -6.786816120147705), (257, ' a', -9.276606559753418), (3671, ' negative', -2.2589974403381348), (2712, ' impact', -12.584653854370117), (322, ' on', -9
.63003921508789), (2227, ' children', -8.899323463439941), (570, ' because', -14.396228790283203), (498, ' if', -7.654298305511475), (321, ' we', -5.693689823150635), (1949, ' 
consider', -10.693066596984863), (3642, ' books', -13.391609191894531), (11, ',', -8.181915283203125), (51014, '<|13.00|>', -5.572175025939941), (51014, '<|13.00|>', -3.1929244
995117188), (562, ' when', -inf), (436, ' they', -5.740912437438965), (1401, ' read', -7.83854341506958), (3642, ' books', -12.358419418334961), (11, ',', -6.387020587921143), 
(50257, '<|endoftext|>', -11.639397621154785)]
ERROR= Got infinite logprob among (24) [(286, ' I', -inf), (519, ' think', -5.2494893074035645), (8815, ' television', -16.253812789916992), (815, ' may', -10.851532936096191),
 (362, ' have', -6.786816120147705), (257, ' a', -9.276606559753418), (3671, ' negative', -2.2589974403381348), (2712, ' impact', -12.584653854370117), (322, ' on', -9.63003921
508789), (2227, ' children', -8.899323463439941), (570, ' because', -14.396228790283203), (498, ' if', -7.654298305511475), (321, ' we', -5.693689823150635), (1949, ' consider'
, -10.693066596984863), (3642, ' books', -13.391609191894531), (11, ',', -8.181915283203125), (51014, '<|13.00|>', -5.572175025939941), (51014, '<|13.00|>', -3.1929244995117188
), (562, ' when', -inf), (436, ' they', -5.740912437438965), (1401, ' read', -7.83854341506958), (3642, ' books', -12.358419418334961), (11, ',', -6.387020587921143), (50257, '
<|endoftext|>', -11.639397621154785)]
```
