### ISSUE TITLE
Is there a way to use it with whisper.cpp

### ISSUE THREAD

**Issue by bitsmakerde** [linto-ai/whisper-timestamped#150]
Hi,

gerade work thank you.

Is there a way to use it together with [whisper.cpp](https://github.com/ggerganov/whisper.cpp) for developing an iOS app?

Thanks

**Comment by Jeronymous** [comment]
No.
whisper-timestamped is a wrapper around openai-whisper.
So this is rather out of scope here.

But out of curiosity, what are the features you are interested in that whisper.cpp does not have?

**Comment by bitsmakerde** [comment]
Thank you. 

I want detect filler words. But this not works good with whisper cpp. I tried it with a prompt.
