### ISSUE TITLE
Cannot find audio file

### ISSUE THREAD

**Issue by JamesSatherley** [linto-ai/whisper-timestamped#151]
For some reason, my audio file cannot be found;

![image](https://github.com/linto-ai/whisper-timestamped/assets/72740217/8008ae96-4eb2-433c-b00d-a198294d05f4)

Despite seeing it exist on the left hand side, it doesn't seem to be able to be found. Thanks

**Comment by Jeronymous** [comment]
It depends from where you run the executable (your are using relative path)

To list files in the current folder (and double check), you can use in python
```
import os
os.listdir(os.path.curdir)
```

**Comment by JamesSatherley** [comment]
I get the following output when running that line about the snippet from my screenshot;

['0.mp3', '1.mp3', '2.mp3', 'background.mp4', 'main.py', 'music.mp3', 'text.mp3', 'ttsPlayer.py', '__pycache__']

The file is definitely there. I've also tried

```
audio = "text.mp3"
results = whisper.transcribe(model, audio)
```

**Comment by Jeronymous** [comment]
To be 100% you can add before load_audio
```
assert os.path.isfile("text.mp3")
```
And note that you can also simply run
```
whisper_timestamped.transcribe(model, "text.mp3")
```

Anyway, I suspect the error is probably something else.
It's probably not talking about the audio file, but about an installation file missing.
Have you followed complete install instruction? In particular, do you have ffmpeg?
