### ISSUE TITLE
Trouble transcribing list of files

### ISSUE THREAD

**Issue by rbgreenway** [linto-ai/whisper-timestamped#154]
I've got a simple script that attempts to transcribe a list of files, but the behavior seems odd to me.  It appears to reload something (it's a different size every time) for each new file to transcribe.  Not sure what that is.  Then it usually crashes my machine while iterating through the files.  Here's the code:

```
import whisper_timestamped as whisper

model = whisper.load_model("large-v2", device="cuda")

files = ["/home/dadmin/audio/test_1.wav",
          "/home/dadmin/audio/test_2.wav",
          "/home/dadmin/audio/test_3.wav",
          ]

for file in files:
    audio = whisper.load_audio(file)

    result = whisper.transcribe(model, audio, language="en",
                                beam_size=5, best_of=5, 
                                 temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0), 
                                 vad=True, detect_disfluencies=True)
    print(result)
```
Ubuntu 20.04
python 3.11.7
two 3090 gpus installed

I'd like to use this as a possible replacement for WhisperX that I'm currently using with Nvidia Triton Server.  In this use case, the model is loaded once (when initialized) and many subsequent transcribe requests are made against that model.  That said, I'd like to figure out what the delays are related to when prepping for a transcription operation.

I'm sorry I don't have more details on the crashing, e.g. a log or error messages.  I'm using TeamViewer to remote into this machine, and behavior is: gui freezes, TeamViewer disconnects, and when I reconnect, it's as though I logged out or the system rebooted...i.e. a fresh new session is started.

**Comment by Jeronymous** [comment]
I suspect you say that it's reloading something every time because you see the progress bar.
Is that it? (the progress bar indicates a "frames/s" rate on the right).
Note that you can use "verbose=None" if you want to avoid it.

Concerning the crash, I am sorry about the inconvenience. Can you check VRAM consumption to check whether it's memory overflow or not?

**Comment by rbgreenway** [comment]
@Jeronymous - thanks for the quick response.  Yes, I imagine my crashing issue is mine to resolve.  Probably something related to my hardware setup or configuration...not a VRAM issue in this case...already checked that.  However, I wanted to make sure that there wasn't something obvious in my code/approach that was wrong.  

From a speed standpoint, after adding "verbose=None", the delay between transcriptions seems to be gone.  That said, and after a bit more testing, I'll see if I can get Triton to serve it...should be doable.

Thank you for this repo.  Your work is excellent
