### ISSUE TITLE
Transcription contains duplicated fragments

### ISSUE THREAD

**Issue by romanzoniit** [linto-ai/whisper-timestamped#16]
Tested on the 'medium' model
Got duplicate fragments
But whisper recognized it well.
`{"text": " Вместе с вами мы будем делать оборудование. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое. И мы будем делать оборудование, чтобы вы могли увидеть, что это такое.",`

whisper:
`{ "text": " Ну, одна, двухкомнатная интересует. Ну, я мужчина один. Тридцать три года русский. Сегодня вечером. Да, да, да. Да, да, но длительный срок. Ну, полгода, год. Нету, нету. Да, да, да. Борис. Да, конечно, какая вот, 50%. Да, да, да, я в курсе. Спасибо большое.",`

**Comment by Jeronymous** [comment]
This is probably due to the fact that whisper use temperature fallback and beam search, while it's currently not supported by whisper-timestamped (see issue #10, it's WIP).

Can you try whisper with options
```
--model tiny --beam_size None --temperature_increment None
```
Tell us if you see the duplicate fragments.
If you see it, then your problem will be solved when issue #10 will be solved

**Comment by Jeronymous** [comment]
@romanzoniit You can now use option `--accurate` in `whisper_timestamped` to reproduce default options of `whisper` (see README for more information).
Can you please check if that solves this issue for you?

**Comment by Jeronymous** [comment]
I think this issue is solved. Don't hesitate to re-open if it's still an issue after my last comments

**Comment by romanzoniit** [comment]
> @romanzoniit You can now use option `--accurate` in `whisper_timestamped` to reproduce default options of `whisper` (see README for more information). Can you please check if that solves this issue for you?

how to use this in python, not in console

**Comment by Jeronymous** [comment]
It's explained in the README
> By default, all options that require several steps of decoding are disabled, in favour of an efficient decoding strategy. Use ```beam_size=5, best_of=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)``` for Whisper default.
