### ISSUE TITLE
Loading finetuned model serialized with several shards

### ISSUE THREAD

**Issue by BlahBlah314** [linto-ai/whisper-timestamped#160]
I've got a finetuned whisper model on hugging face and I would like to try timestamped and diarization on it. But when loading it, it searches for a pytorch_model.bin, but my model doesn't have a pytorch.bin but has safetensors. How can I resolve this issue ?

**Comment by Jeronymous** [comment]
Can you give some code to reproduce?

**Comment by LaurinmyReha** [comment]
```
from transformers import WhisperForConditionalGeneration
model=WhisperForConditionalGeneration.from_pretrained("your_model_dir")
model.save_pretrained("your_model_dir", safe_serialization=False, max_shard_size= '10GB') 
```

**Comment by Jeronymous** [comment]
What is "your_model_dir" in your case?
You mentioned "finetuned whisper model on hugging face", I thought you were using a model that is on Hugging Face.

Also there is no whisper_timestamped in your code.
Is it possible to have a code to reproduce how you load the model in whisper_timestamped? (the code that throws an error related to a missing "pytorch_model.bin" file I guess)

**Comment by LaurinmyReha** [comment]
exactly. Increase the max_shard_size to something larger and you should be fine i think. 10GB as in the example will definately be enough :) 

`model.save_pretrained("your_model_dir", safe_serialization=False, max_shard_size= '10GB') `

**Comment by LaurinmyReha** [comment]
```
from transformers import WhisperForConditionalGeneration
model=WhisperForConditionalGeneration.from_pretrained("BlahBlah314/whisper_LargeV3FR_ft-V1")
model.save_pretrained("path_to_where_you_want_to_safe_your_bin", safe_serialization=False, max_shard_size= '10GB') 
```

exactly. I think this should do the conversion.... there is probably a better way but this seemed easiest to me. After that add the .bin file to where your safetensor file resides ( in your case the huggingface hub) and you should be able to load the model :)

**Comment by BlahBlah314** [comment]
Thank you ! I'll try that way

**Comment by Jeronymous** [comment]
Thanks both ! 
I figured out how to support shared models and safetensors format.

@BlahBlah314 You should be able to use your "BlahBlah314/whisper_LargeV3FR_ft-V1" with the new version (1.14.4)

**Comment by LaurinmyReha** [comment]
very cool!! thanks for the quick update!
