### ISSUE TITLE
Could it be possible to apply the same technique to the whisper API?

### ISSUE THREAD

**Issue by maximerdy1** [linto-ai/whisper-timestamped#164]
Hi there, I'm not sure whether it's relevant to open an issue about that but it's the only way I know of to get in touch with you, but please feel free to close it if it's not.
I'm developing something that I love and that needs transcription. I'm using the whisper models locally with the word level timestamps, but it's very cpu intensive and it costs me a lot when on a virtual machine because I need a lot of CPU.
I'd therefore love to use the whisper API, which would cost me wayyyy less, but with the API, the word-level timestamps are, as far as I know, not available, and I really need them for what I'm building.
Since I've seen you've found a workaround with the whisper models, I'm wondering whether that'd be possible to apply the same technique to the whisper API.
As I'm not the best developer in the world, I'm struggling to understand what you've done on my own, but if you tell me it's possible and you explain me how you did it, I think I might be able to reproduce it, with a bit of your kind help :)
Thank you very much.

**Comment by Jeronymous** [comment]
Hello. Let's clarify first: what do you call the "whisper API"? 
OpenAI API? Can you put the link?

**Comment by maximerdy1** [comment]
Thanks for your responsiveness!
The OpenAI API also offers transcription, using the "large" whisper model, and the costs are way less than the cost of the required CPU, but it doesn't support word-level timestamps yet.
Here is the link: https://platform.openai.com/docs/guides/speech-to-text

**Comment by Rayan-Allali** [comment]
@maximerdy1 you can use fastapi and make it as api

**Comment by Jayavel-S** [comment]
Hey! I am also looking for this functionality. I need to utilize the Translations endpoint from the OpenAI's API.

**Comment by mkmohangb** [comment]
The OpenAI API does support word level granularity, ```timestamp_granularities=["word"]```, check the section under Timestamps.

**Comment by Jayavel-S** [comment]
We did check it. But it isn't for the translation endpoint. The ideal usage would be to have at least segment-level timestamps generated in the translation's endpoint.
