### ISSUE TITLE
CPU only light install links are broken?

### ISSUE THREAD

**Issue by al3kq** [linto-ai/whisper-timestamped#167]
Having trouble install the light CPU only versions of torch dependencies. Are the links broken?

**Comment by Jeronymous** [comment]
What is given in the README is just an example command.

But I still see the "1.13.1" version in https://download.pytorch.org/whl/torch_stable.html

What exactly is your  command and your error ?

**Comment by al3kq** [comment]
It looks like something is off with my Python versioning related to the torch install although I tried a couple python versions (3.8, 3.11). I decided to wrap it in an API and am trying to find somewhere to host it with a GPU.

**Comment by Jeronymous** [comment]
You can try a more recent torch version.

1.13.1 was just given as an example. I'm running with torch 2 and it works smoothly
