### ISSUE TITLE
How to use cuda?

### ISSUE THREAD

**Issue by eliich** [linto-ai/whisper-timestamped#174]

**Comment by Jeronymous** [comment]
The device is chosen when loading the model.

```
import whisper_timestamped as whisper
model = whisper.load_model("tiny", device="cuda")
```

and there is an option `--device` in the CLI

(same syntax as pytorch supported: "cuda:0", ...)

**Comment by eliich** [comment]
> The device is chosen when loading the model.
> 
> ```
> import whisper_timestamped as whisper
> model = whisper.load_model("tiny", device="cuda")
> ```
> 
> and there is an option `--device` in the CLI
> 
> (same syntax as pytorch supported: "cuda:0", ...)

It seems that when I do that cuda is not available. which is weird considering I used whisper and whisperX with cuda just fine
