### ISSUE TITLE
cuda is not available?

### ISSUE THREAD

**Issue by eliich** [linto-ai/whisper-timestamped#177]
Hello ive installed whisper, and whisperX and am able to use cuda with ease, but I am not able to do it for this package? Do I need to downgrade or something? Just wondering how I can manage multiple versions as I still need the other version for whisper and whisperX

**Comment by Jeronymous** [comment]
> I am not able to do it for this package?

What is the problem? It is not using the GPU by default, or you have errors?

If it's not using the GPU by default (it should, if CUDA is available), you can try `load_model(..., device="cuda")` (or `--device=cuda` with the CLI).

whisper-timestamped uses CUDA thru torch.

No need to downgrade anything

**Comment by Jeronymous** [comment]
I already gave this answer in https://github.com/linto-ai/whisper-timestamped/issues/174 ...
Please stop closing and re-opening the same issue, and keep one discussion thread

**Comment by Jeronymous** [comment]
I don't see any reason why CUDA would work with whisperX and not whisper-timestamped, as both are using torch.

If you have an error message, please copy-paste it.

**Comment by eliich** [comment]
When I just run the is cuda available test, I get that it is not available
```
import torch

def test_cuda_pytorch():
    # Check if CUDA is available
    if torch.cuda.is_available():
        print("CUDA is available. Using GPU.")
        
        # Get CUDA device name
        device_name = torch.cuda.get_device_name(torch.cuda.current_device())
        print(f"Device name: {device_name}")

        # Create a tensor and move it to GPU
        tensor = torch.randn(3, 3)
        tensor = tensor.to('cuda')

        # Perform a simple operation
        result = tensor * tensor
        print("Result of the operation:")
        print(result)

        print("CUDA and PyTorch are working correctly!")
    else:
        print("CUDA is not available. Please check your installation.")

if __name__ == "__main__":
    test_cuda_pytorch()
```

**Comment by eliich** [comment]
> Collaborator

Can I run it WSL? or docker should that work?

**Comment by Jeronymous** [comment]
WSL and docker : yes, it works, as long as nvidia tools are correctly installed (for instance for docker, you need "nvidia-container-toolkit" to be installed, and to create the docker containers with options `--gpus all`)

You just need investigate why torch is not detecting your GPU.
Is it just a problem torch.cuda.is_available (if torch.cuda.current_device() is working for instance)? ...

> you can try load_model(..., device="cuda") (or --device=cuda with the CLI).

You haven't answer whether/how this fails.

**Comment by Jeronymous** [comment]
Also, what gives
```
pip show torch
```
?

It could be that your torch is installed for CPU only

**Comment by Jeronymous** [comment]
Closing after some time of inactivity
