### ISSUE TITLE
There are plans to use ctranslate2 to speed up? similar to faster-whisper

### ISSUE THREAD

**Issue by pxEkin** [linto-ai/whisper-timestamped#181]

**Comment by Jeronymous** [comment]
No, sorry.
whisper-timestamped is just a wrapper around openai-whisper.
See https://github.com/linto-ai/whisper-timestamped/issues/40 and https://github.com/linto-ai/whisper-timestamped/issues/165 and

**Comment by Jeronymous** [comment]
.
