### ISSUE TITLE
When the transcription progress reaches 100%, it takes a long time to show the result, sometimes even up to 10 minutes.

### ISSUE THREAD

**Issue by sulutian** [linto-ai/whisper-timestamped#185]

**Comment by Jeronymous** [comment]
Yes, because the progess bar comes from the openai-whisper backend.
Then alignement the alignement is done, and can take roughly the same time (under some conditions).

I guess that the "even up to 10 minutes" occur when the transcription itself took 10 minutes or more.

**Comment by sswam** [comment]
You could potentially add a 2nd progress bar to the alignment process, so that people can see what's happening.

**Comment by alexandervlpl** [comment]
In my case (transcribing a 30 min audio track on CPU) the Whisper progress bar took ~3 hours, the alignment another 11. :fearful: It would be nice to make it clear in the README that this is significantly slower than pure Whisper.
