### ISSUE TITLE
What is it (very slowly) trying to download?

### ISSUE THREAD

**Issue by ulatekh** [linto-ai/whisper-timestamped#187]
I just installed whisper_timestamped, trying to find a variant of Whisper that'll generate more accurate SRT timestamps (because the ones Whisper generates are only accurate to a second & I have to hand-edit all of them...ugh).

It appears to be finding the model I downloaded previously for OpenAI's Whisper, avoiding a ~3 GB download of large-v2, but then it starts downloading something else; it doesn't say what it is. I wouldn't care normally, but it's *very* slow...

```
14500/741619 [12:14<10:14:11, 19.73frames/s]
```

What 741,619 byte file is it trying to download? Is there somewhere else I can go to get it, that won't take literally 10 hours?

**Comment by ulatekh** [comment]
whisper_timestamped [audio file] --model_dir [non-default location] --language en --model large-v2 --output_format srt

**Comment by Jeronymous** [comment]
Thank you.

So indeed, if there was a download, it was the large-v2 model.

The progress bar you see, that indicates a "`frames/s`" rate is just the progress bar of the transcription.

Yes, it can be long, on long audio / without GPU...

Sorry for the inconvenience

**Comment by ulatekh** [comment]
Oh...I didn't realize that was the progress bar for the transcription. If it is, that's fine. It just wasn't labeled, and other Whisper variants I've run across don't do that; instead, they spit out words/timestamps/etc. as an indicator of progress.
