### ISSUE TITLE
Output filenames aren't consistent with original openai-whisper implementation

### ISSUE THREAD

**Issue by lutangar** [linto-ai/whisper-timestamped#189]
### `openai-whisper`
```sh
whisper "./video_short.mp4" --model tiny --output_format all --output_dir "./transcripts"
```
Output the following files:
```
video_short.json
video_short.srt
video_short.tsv
video_short.txt
video_short.vtt
```

### `whisper-timestamped`
```sh
whisper_timestamped "./video_short.mp4" --model tiny --output_format all --output_dir "./transcripts"
```
Output the following files:
```
video_short.mp4.csv
video_short.mp4.srt
video_short.mp4.tsv
video_short.mp4.txt
video_short.mp4.vtt
video_short.mp4.words.csv
video_short.mp4.words.json
video_short.mp4.words.srt
video_short.mp4.words.tsv
video_short.mp4.words.vtt
```

### Difference

 `opena-ai` doesn't include original audio / video **extension** in the output filenames.

> EDIT: Also just noticed the `json` version seems to be missing from `whisper_timestamped` output files.

**Comment by Jeronymous** [comment]
Indeed, whisper-timestamped reproduces an old behaviour of openai-whisper.
And we think it is good as it is, to include the extension of input files in the ouput files (for someone who wants to test the transcription depending on the audio format for instance).
The source is opened, so it can be easily modified.
