### ISSUE TITLE
Output  syntaxically invalid vtt file (header appears twice)

### ISSUE THREAD

**Issue by lutangar** [linto-ai/whisper-timestamped#190]
Running :
```sh
whisper_timestamped "./tests/fixtures/video_short.mp4" --model tiny --output_format all --output_dir "./test-transcript"
```

> ```
> Detected language: English
> 100%|████| 501/501 [00:00<00:00, 879.54frames/s]
> Detected language: English
> ```

Produce the following  `vtt` file :
```
WEBVTT

WEBVTT

00:02.480 --> 00:02.500
you
```

Which is invalid, since the header is appearing twice.
Other formats (`srt` for example) don't seem to be impacted.

**Comment by Jeronymous** [comment]
Thanks for reporting @lutangar 
That was the border effect of some ugly hack.
It's now fixed (in version 1.15.4)
