### ISSUE TITLE
Timestamps not provided per-word for Chinese/Japanese/Korean

### ISSUE THREAD

**Issue by blackears** [linto-ai/whisper-timestamped#194]
whisper_timestamped does not return statistics for individual words and the entire "words" array under each segment is missing.  Instead you just get a chunk of about 10 words in a row and start and end times for the whole segment.  Is there any way to get individual word timings?

**Comment by Jeronymous** [comment]
Individual word timings should be in the output.
Can you show the code / command you use, and the output?

**Comment by Jeronymous** [comment]
@blackears To show reproduction, you can use this audio in Japenese: [tests/data/japanese.mp3](https://github.com/linto-ai/whisper-timestamped/blob/master/tests/data/japanese.mp3)
I tested, and see timestamps for each Japanese word/character

**Comment by blackears** [comment]
Okay, it does seem to be providing per word timestamps after all. Not sure why I was not seeing  them earlier.  Sorry about this.
