### ISSUE TITLE
whisper-timestamped 1.15.4 not compliant with openai-whisper 20240930

### ISSUE THREAD

**Issue by dchapelet** [linto-ai/whisper-timestamped#219]
Hello,
I updated to the latest openai-whisper version (_20240930_) but now I have an error with whisper-timestamped v1.15.4.
The error returned is a "None type object with Shape" issue
To work around, I had to rollback openai-whipser to 20231117.
Thank you very much for your help

**Comment by Jeronymous** [comment]
duplicate of https://github.com/linto-ai/whisper-timestamped/issues/212
