### ISSUE TITLE
Verbose option does not support None (no output)

### ISSUE THREAD

**Issue by kamranjon** [linto-ai/whisper-timestamped#25]
In the original Whisper `transcribe` implementation providing `None` to the `verbose` option suppresses everything, [which is explained here](https://github.com/openai/whisper/blob/main/whisper/transcribe.py#L45). I believe it is [this line here](https://github.com/linto-ai/whisper-timestamped/blob/master/whisper_timestamped/transcribe.py#L259), which overrides the `None` behavior and subsequently there is no option to have no output whatsoever (providing None shows the progress bar and language, providing False also shows the progress Bar and Providing True does not show the progress bar but displays the list of word-level timestamps). 

It would be ideal if there was an option to suppress all output from the transcribe method.

**Comment by kamranjon** [comment]
I think I misunderstood and the progress bar is not actually going through stdout? In any case, I don't think this is really an issue. Sorry for the confusion.

**Comment by Jeronymous** [comment]
Thanks for spotting @kamranjon 
I fixed that
