### ISSUE TITLE
Delay in the word level transcription

### ISSUE THREAD

**Issue by ItakeLs** [linto-ai/whisper-timestamped#27]
Hello I'm not sure if this is a limitation of whisper or a bug, but sometimes the sentences/segments are delayed and then happen all at once.

This video can reproduce the delay: [youtube](https://www.youtube.com/watch?v=PCS-dvQvXIw)
Downloaded from the mp4 from here: [youtube downloader](https://yt1ss.net/en16?q=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPCS-dvQvXIw)

I think it happens for sections that are followed with no speech/audio sections.  In this particular video, there is an example of it occurring around the 24-second mark, and the text for that segment appears later all at once. 

I used whisper large-v1 with ```temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)```, ```beam_size=5```, ```best_of=5```, ```condition_on_previous_text=False```

**Comment by Jeronymous** [comment]
Thanks a lot @ItakeLs for opening this issue and providing a reproducible example.
I'll check if I can do something about it.

**Comment by ItakeLs** [comment]
No problem, just to confirm. I tried to see if it was a limitation of whisper, however, when using the [word-level-timestamp branch](https://github.com/openai/whisper/tree/word-level-timestamps) of whisper it doesn't occur.

I tried reproducing the error and I can confirm it occurs in segments that happen just before sections of the audio where there is no detected speech.

**Comment by Jeronymous** [comment]
Thank you so much again @ItakeLs 

I've just added new heuristics that should solve the issue.
