### ISSUE TITLE
Specific functions don't work.

### ISSUE THREAD

**Issue by xaxole98** [linto-ai/whisper-timestamped#29]
![image](https://user-images.githubusercontent.com/122705252/217193211-6e68d1b3-82a1-421f-a79c-b95abce36f5f.png)
You can help me please? And thank for you work

**Comment by misutoneko** [comment]
I'm not the author, but you need to replace PUNCTUATIONS_WITH_WORDS with a boolean value.
(It defaults to True)

And yes, thank you for the work Jeronymous & co. on my behalf as well :D

**Comment by Jeronymous** [comment]
Thank you @misutoneko 

Indeed @xaxole98 you have to call `--punctuations_with_words True` (resp. False) instead of `--punctuations_with_words 1` (resp. 0).
And the default is already True.

**Comment by xaxole98** [comment]
Thank you! Working right now!
