### ISSUE TITLE
Suggestion: Use VAD to improve over Whisper's segment timestamps estimation

### ISSUE THREAD

**Issue by Jeronymous** [linto-ai/whisper-timestamped#36]
See discussion #22

**Comment by mmichelli** [comment]
Thanks for the great work :)

I'm using your library for meetings, which would work well with the VAD [ArxiV preprint (https://arxiv.org/abs/2303.00747) chunking described in the paper.

**Comment by mmichelli** [comment]
Is there a way to interact with whisper-timestamped, passing batches of audio?

**Comment by Jeronymous** [comment]
Thank you @mmichelli for the reference about the use of VAD by WhisperX.

It's not really possible to process batches of audio in whisper-timestamped, because it's calling OpenAI whisper implementation which does not have this capability (contrarily to HuggingFace implementation that can process batches into a single call).
It sounds a topic for another more general issue/suggestion.

Multi-threading is of course an option to process efficiently several audio files (which might be much more efficient than batching with padding, when the audio have very different length).
Batching internally on VAD segments is a different thing, that makes a lot of sense.

**Comment by mmichelli** [comment]
I was thinking of segmenting on VAD and passing the batches to whisper-timestamped.

**Comment by Jeronymous** [comment]
This is being addressed in branch `features/vad_before_whisper` https://github.com/linto-ai/whisper-timestamped/pull/54

**Comment by Jeronymous** [comment]
There is now an option `--vad True/False` (False by default) to perform VAD before sending to Whisper
