### ISSUE TITLE
Make Whisper Requirement more flexible to be able to use a specific Whisper version (as some breakages were introducted in 20230306)

### ISSUE THREAD

**Issue by kamranjon** [linto-ai/whisper-timestamped#48]
The [latest changes to whisper](https://github.com/openai/whisper/commit/500d0fe9668fae5fe2af2b6a3c4950f8a29aa145) (adding word-level timestamps) have added [a dynamic requirement](https://github.com/openai/whisper/blob/main/setup.py#L15) (triton) that breaks if you don't have a specific environment. If we could change the `requirements.txt` in whisper-timestamped to target a specific whisper version (preferably before these latest whisper changes, [maybe the last stable release on jan 24](https://github.com/openai/whisper/releases/tag/v20230124)?) - that would be much more stable and would not result in breakages.

**Comment by Jeronymous** [comment]
Thanks for notifying.
Indeed targeting a specific whisper version would be more future-proof.
However, using whisper version 20230306 would be better than the previous version 20230124, because of some bug resolutions that are useful (avoid an infinite loop for instance).

I'm currently  testing and for now I don't see any breakage with the new version 20230306.

Can you please clarify what you refer to with "breaks if you don't have a specific environment"? Any specific error message during the setup?

**Comment by kamranjon** [comment]
@Jeronymous this is the exact error I get: `Could not find a version that satisfies the requirement triton>=2.0.0.dev20221202 (from openai-whisper) (from versions: none)`

Even just pinning whisper to `git+https://github.com/openai/whisper@3e1780f` - the commit right before this change would be great.

**Comment by kamranjon** [comment]
If you are testing on osx you will not see this error, it is a result of this portion of code that was added:
```python
if sys.platform.startswith("linux"):
    triton_requirement = "triton>=2.0.0.dev20221202"
    try:
        import re
        import subprocess
        version_line = subprocess.check_output(["nvcc", "--version"]).strip().split(b"\n")[-1]
        major, minor = re.findall(rb"([\d]+)\.([\d]+)", version_line)[0]
        if (int(major), int(minor)) < (11, 4):
            # the last version supporting CUDA < 11.4
            triton_requirement = "triton==2.0.0.dev20221011"
    except (IndexError, OSError, subprocess.SubprocessError):
        pass
requirements = []
if sys.platform.startswith("linux"):
    triton_requirement = "triton>=2.0.0.dev20221202"
    try:
        import re
        import subprocess
        version_line = subprocess.check_output(["nvcc", "--version"]).strip().split(b"\n")[-1]
        major, minor = re.findall(rb"([\d]+)\.([\d]+)", version_line)[0]
        if (int(major), int(minor)) < (11, 4):
            # the last version supporting CUDA < 11.4
            triton_requirement = "triton==2.0.0.dev20221011"
    except (IndexError, OSError, subprocess.SubprocessError):
        pass
    requirements.append(triton_requirement)
    ```
    
    I'm a bit surprised that this made it in to main

**Comment by kamranjon** [comment]
And for what it's worth i think this is very platform specific - so if you are using an arm image of linux - pip will not be able to find triton as a pip dependency - so this fails.

**Comment by Jeronymous** [comment]
> Even just pinning whisper to git+https://github.com/openai/whisper@3e1780f - the commit right before this change would be great.

This would make sense specifically for ARM linux, before the bug is solved on Whisper side.

I see that you reported the issue well https://github.com/openai/whisper/discussions/1048
Let's hope that it gets solved soon.

For now, I see nothing preventing from installing whatever version of whisper works for you, before installing whisper-timestamped.

**Comment by kamranjon** [comment]
@Jeronymous thank you for making the `requirements.txt` more flexible! This makes it easy to specify a whisper version that works with our environment.

**Comment by Jeronymous** [comment]
OK so in the end:
- Version 20230306 introduced a breakage on ARM linux, as reported by @kamranjon on https://github.com/openai/whisper/discussions/1048
- It also introduces some bugs, which can be a good reason to use another specific older version
   - https://github.com/openai/whisper/discussions/1046
   - (and I am seeing problems of repeated text around silences both with 
- Version 20230306 also brings some backward compatibility issues with whisper-timestamped, but that will be addressed in another dedicated issue I'll open
- The python requirement of whisper-timestamped was linking openai-whisper package to the github repo, which was forcing to prefer the latest version. This link was removed, so the requirement is more flexible and allow anybody to use any version / checkpoint of Whisper.
