### ISSUE TITLE
The result is almost lost when I use whisper timestamped.

### ISSUE THREAD

**Issue by YeDaxia** [linto-ai/whisper-timestamped#67]
enviroment:

```
openai-whisper           20230314
whisper-timestamped      1.12.7
```

part code:
```
import whisper_timestamped as whisper

audio = whisper.load_audio(audioFile)
model = whisper.load_model('large-v2')
result = whisper.transcribe(model, audio, language=lang)
```

Here I use result["segments"] to generate subtitle:

lost result:

![img_v2_0488112c-653b-4ca4-a915-9e6af2f8548g](https://user-images.githubusercontent.com/4317015/226788161-8dfa8554-c501-44f2-9370-7b868a9818de.jpg)

![img_v2_473eabda-cffc-4c82-8ffe-d4be02fa967g](https://user-images.githubusercontent.com/4317015/226788344-48755faf-fc57-4bc4-b66d-bbfff1272c2a.jpg)

without whisper-timestamped:

![img_v2_a1f618fc-10d0-4849-9a97-1c7a85042c0g](https://user-images.githubusercontent.com/4317015/226789051-deadaaa9-3f7f-4ec2-9234-c72b7b162d0a.jpg)

Am I use the wrong version ?

**Comment by Jeronymous** [comment]
Default options are not the same in whisper-timestamped and in whisper.
That could be it.

Can you try using the following last 3 options:
```
result = whisper.transcribe(model, audio, language=lang,
   beam_size=5, best_of=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)
)
```

**Comment by YeDaxia** [comment]
> Default options are not the same in whisper-timestamped and in whisper. That could be it.
> 
> Can you try using the following last 3 options:
> 
> ```
> result = whisper.transcribe(model, audio, language=lang,
>    beam_size=5, best_of=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)
> )
> ```

I try to add the options above, it seems no change.

**Comment by mmichelli** [comment]
I get the same type of problem. 

The error: 
`Too much text (138 tokens) for the given number of frames (106) in: <|0.00|>Framdrift i forhold til denne dataen er at vi har gjennomgang i juni. Vi har avtalt med ungdomsrådet at vi skal ha en workshop hvor ungdommen inviterer ulike bidragsytere til å ha en prosess knyttet til bildet vi ser foran oss. Hva ser vi for oss som viktige tiltak? Vi gir en tilbakemelding i det gjennom ungdomsrådet. Så må denne ungdata ses i sammenheng med andre tilbakemeldinger vi får.<|1.62|>`

The output: 
`Framdrift i forhold til denne`

**Comment by Jeronymous** [comment]
I pushed a new version that should fix the problem observed by @mmichelli 

The issue of @YeDaxia is not clear to me.
I would need more information to reproduce and understand the issue (an audio along with all the options used).
