### ISSUE TITLE
Install whisper-timestamped with only CPU dependencies

### ISSUE THREAD

**Issue by agorman** [linto-ai/whisper-timestamped#68]
Is there a way to install whisper-timestamped with only dependencies required for CPU processing?

[This change to requirements ](https://github.com/linto-ai/whisper-timestamped/commit/efb01e522fafca33a96d37bb84f3ede13e3316f0) adds some very large packages as dependencies that don't appear to be required when not using GPU. I'm avoiding this now by doing the following.

Install whisper avoiding GPU deps
~~~
pip install torch-1.13.1+cpu-cp39-cp39-linux_x86_64.whl
pip install git+https://github.com/openai/whisper.git
~~~

Install whisper-timestamped avoiding GPU deps
~~~
pip install Cython dtw-python
pip install --no-deps git+https://github.com/linto-ai/whisper-timestamped
~~~

This isn't a great solution for whisper-timestamped because if you add other needed dependencies to requirements.txt it will fail.

**Comment by PlkMarudny** [comment]
Actually, this gives an error:
```
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118)
```
