### ISSUE TITLE
AssertionError with --vad, only with medium model

### ISSUE THREAD

**Issue by misutoneko** [linto-ai/whisper-timestamped#80]
The VAD option seems generally very helpful, but here's one clip it couldn't handle.
Looks like this only happens with the medium model. The clip doesn't contain any speech.

`
$ CUDA_VISIBLE_DEVICES=-1 /usr/local/bin/whisper_timestamped --threads 1 --language en --device cpu --output_format srt,json --model medium --vad True --output_dir . clip_184_24549.wav
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 294/294 [05:39<00:00,  1.16s/frames]
WARNING:whisper_timestamped:Got start time outside of audio boundary
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 11, in <module>
    load_entry_point('whisper-timestamped==1.12.15', 'console_scripts', 'whisper_timestamped')()
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped-1.12.15-py3.8.egg/whisper_timestamped/transcribe.py", line 2281, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped-1.12.15-py3.8.egg/whisper_timestamped/transcribe.py", line 259, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_efficient(model, audio,
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped-1.12.15-py3.8.egg/whisper_timestamped/transcribe.py", line 850, in _transcribe_timestamped_efficient
    may_flush_segment()
  File "/usr/local/lib/python3.8/dist-packages/whisper_timestamped-1.12.15-py3.8.egg/whisper_timestamped/transcribe.py", line 703, in may_flush_segment
    assert chunck_indices[i_token_start:i_token_end] == tokens, f"Inconsistent token list {tokenizer.decode_with_timestamps(chunck_indices[i_token_start:i_token_end])} != {tokenizer.decode_with_timestamps(tokens)}"
AssertionError: Inconsistent token list <|endoftext|> != <|10.50|><|endoftext|>
`

[clip_184_24549.zip](https://github.com/linto-ai/whisper-timestamped/files/11237642/clip_184_24549.zip)

**Comment by Jeronymous** [comment]
Thanks a lot @misutoneko for reporting and giving clearly all information to reproduce :+1: 

This should work without error now.

However the transcription is just hallucination on this small musical background, you might want to use `--accurate` option.

Note: I had some troubles to reproduce, because you seem to be using an old version of whisper (20230124, or before).
So you might want to upgrade whisper to a more recent version. Or not... (everyone is free to use the version he wants to, that's the beauty of whisper-timestamped to provide word timestamp for any version of whisper).

**Comment by misutoneko** [comment]
Yes I can confirm that it works now, thank you.
You're quite right, I have the old 20230124 version of openai-whisper - It was recommended a while back, but that's probably over a month ago already :D
As for --accurate, it's too slow for my aged hardware so I have a different method for dealing with hallucinations: I reprocess the "suspicious" portions of the file with --language it (italian) and if the result says something about "sottotitoli" I know it's hallucinating :D
And just to clarify, my source material is usually in english (it's unlikely there's any actual italian speech in there).
