### ISSUE TITLE
Can't install on M2 Mac

### ISSUE THREAD

**Issue by boxabirds** [linto-ai/whisper-timestamped#83]
Hi whether I use `pip` or directly with `python setup.py install` I'm getting a dependency issue on my M2 Mac. 

```
error: Could not find suitable distribution for Requirement.parse('onnxruntime')
```

`onnxruntime` does not seem to support M2 Macs at the moment. `onnxxruntime-silicon `also appears to be a dead end (also saying there is no version available)

I used `whisper-timestamped` a few months ago (v 1.7.2) and installation / execution worked fine on my M2 Mac. Could this be a new dependency that prevents usage on M2 Macs? Was onnxruntime always a dependency?

**Comment by Jeronymous** [comment]
Indeed dependencies changed when an option to run VAD was added.
But it's a pity to force those dependencies for people not using the VAD option.
Also the method used for VAD may change soon (see #74).

So I ended up removing onnxruntime from the requirements, and mentioned that in the README for people using the VAD option.

**Comment by boxabirds** [comment]
BTW I did a fresh install, being careful to installing onnxruntime first, and only against Python 3.9 as I had read somewhere that in general it's a good idea to avoid running against cutting edge python releases when working in the ML space and all worked well.
