### ISSUE TITLE
error for long (1 hr) hindi video - used large-v2 whisper model

### ISSUE THREAD

**Issue by rairavi** [linto-ai/whisper-timestamped#87]
97%|█████████▋| 157296/162500 [40:30<01:17, 67.37frames/s]
 99%|█████████▊| 160296/162500 [40:55<00:32, 67.39frames/s]
 99%|█████████▊| 160296/162500 [41:10<00:32, 67.39frames/s]
100%|██████████| 162500/162500 [41:40<00:00, 61.43frames/s]
100%|██████████| 162500/162500 [41:40<00:00, 64.98frames/s]
Got inconsistent length for segment 48 (49 != 19). Some words have been ignored.
Traceback (most recent call last):
  File "/data/p/code.py", line 84, in <module>
    result = transcribe(video_converted,language)
  File "/data/p/codeTranscript.py", line 15, in transcribe
    return transcribe_timestamped(audio,language)
  File "/data/p/codeTranscript.py", line 33, in transcribe_timestamped
    result = whisper_timestamped.transcribe(model, audio, language, fp16=False, verbose=False)
  File "/data/p/venv-3.10/lib/python3.10/site-packages/whisper_timestamped/transcribe.py", line 264, in transcribe_timestamped
    transcription, words = remove_last_null_duration_words(transcription, words, recompute_text=True)
  File "/data/p/venv-3.10/lib/python3.10/site-packages/whisper_timestamped/transcribe.py", line 1889, in remove_last_null_duration_words
    raise RuntimeError(f"\"{text}\" not ending with \"{full_word}\"")
RuntimeError: " पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए पर्टिएजार के लिए �" not ending with " लिए"

**Comment by rairavi** [comment]
whisper_timestamped --versions
1.12.17 -- Whisper 20230314 in /Users/python/venv-3.10/lib/python3.10/site-packages/whisper


CPU - Macbook M2 on large-ve, only timestamp=true option rest is defualt

https://www.youtube.com/watch?v=rn64Vf6GEoo

**Comment by Jeronymous** [comment]
Thank you @rairavi 

I've just disabled a dangerous heuristic that was causing this issue, and also possible removing relevant words from the transcriptions.
(it consisted into removing words with empty duration, assuming it was coming from Whisper's hallucinations).

So in a sense that issue is solved
