### ISSUE TITLE
Suggestion to change the way output-files are saved

### ISSUE THREAD

**Issue by oep42** [linto-ai/whisper-timestamped#93]
I did some testing with Whisper-timestamped. When I repeated a test, with the output-files of the first time I ran this test made read-only, I got the error below.

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\whisper_timestamped.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\whisper_timestamped\transcribe.py", line 2333, in cli
    with open(outname + ".srt", "w", encoding="utf-8") as srt:
PermissionError: [Errno 13] Permission denied: 'D:\\Folder\\TEST.mkv.srt'
```

I would suggest, in such a situation when the file to be saved already exists, to save that file with the same filename with an added sequence number, such as "TEST.mkv_2.srt".

**Comment by Jeronymous** [comment]
Thanks for reporting.

I don't like the idea of automatic renaming of output files.
It could produce folders with a lot of mess.

You should rather wonder:
- why are files in read-only mode?
- why do you generate several times the same output? If it's on the same input file, for two runs, why not to use one folder per run? (or delete the folder between two runs?)

**Comment by oep42** [comment]
> why are files in read-only mode?

Because I set it that way. I was doing different test runs with the same source file, and I wanted to compare the output of those test runs. Also, I am used to make files read-only if I want to be sure that nothing happens with it that I may not notice (like overwriting).

> why do you generate several times the same output? If it's on the same input file, for two runs, why not to use one folder per run? (or delete the folder between two runs?)

Not everyone is used to do things in the same way. Next time, I will rename the output files first, before a new test run.

**Comment by Jeronymous** [comment]
OK thanks.

I note that things could be improved regarding how output filenames are set.
For the sake of simplicity, whisper-timestamped reproduces what whisper does (or what did at the beginning, there was a subtle modification in the meantime, that the extension of the input file was removed in the output filename).
But I'm sure there are better options.
