### ISSUE TITLE
CUDA or is it me? Windows.

### ISSUE THREAD

**Issue by pinballelectronica** [linto-ai/whisper-timestamped#96]
I use CUDA all day long with a 4090- This seems to be an outlier.

  File "C:\Users\dave\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I have a very fast CPU(s) so the inference was good enough for me to not notice (sub 30m large-v2 for 1.5 hour video).  Alas, my 4090 wants a part of the action.  I cannot for the life of me figure this out.  

Py 3.10.10
CUDA 12.1
in path
added all the requirements.txt (had most)

using --device "cuda:0"  (literally, with the quotes)

Thanks

**Comment by phineas-pta** [comment]
downgrade to cuda 11.8

pytorch still bad with cuda 12
