### ISSUE TITLE
ok, this is amazing but how can we transofrm it into an API?

### ISSUE THREAD

**Issue by silvacarl2** [linto-ai/whisper-timestamped#98]
ok, this is amazing but how can we transofrm it into an API?

has anyone done this using FastAPI?

**Comment by Aditya3107** [comment]
Yes, i implemented it with fastapi.

**Comment by silvacarl2** [comment]
if you have an example that would be great.

**Comment by Rayan-Allali** [comment]
where can i find exemples?

**Comment by al3kq** [comment]
I am currently hosting this as an API on runpod with good performance from a RTX A4000. Hmu if you want to use it andrewrblee@gmail.com
